=== joorter/CuatroEnRaya/src/BD.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT listapersonas (persona*)>
<!ELEMENT persona (nombre, victorias, logros*)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT victorias (#PCDATA)>
<!ELEMENT logros (logro+)>
<!ELEMENT logro (id, nombrelogro, descripcion, completado)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT nombrelogro (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT completado (#PCDATA)>

=== joorter/CuatroEnRaya/src/Jugadores.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listapersonas SYSTEM "BD.dtd" >
<listapersonas>
    <persona>
        <nombre>Mario</nombre>
        <victorias>5</victorias>
        <logros>
            <logro>
                <id>1</id>
                <nombrelogro>Victoria magistral</nombrelogro>
                <descripcion>Gana una partida</descripcion>
                <completado>true</completado>
            </logro>
            <logro>
                <id>2</id>
                <nombrelogro>Maestro de la victoria</nombrelogro>
                <descripcion>Gana 5 partidas</descripcion>
                <completado>true</completado>
            </logro>
            <logro>
                <id>3</id>
                <nombrelogro>La X marca el lugar</nombrelogro>
                <descripcion>Gana una partida utilizando fichas X</descripcion>
                <completado>true</completado>
            </logro>
            <logro>
                <id>4</id>
                <nombrelogro>O-mazing Victory</nombrelogro>
                <descripcion>Gana una partida utilizando fichas O</descripcion>
                <completado>true</completado>
            </logro>
            <logro>
            	<id>5</id>
            	<nombrelogro>Tablas</nombrelogro>
                <descripcion>Empata una partida</descripcion>
                <completado>false</completado>
            
            </logro>
        </logros>
    </persona>
    <persona>
        <nombre>Josean</nombre>
        <victorias>4</victorias>
        <logros>
            <logro>
                <id>1</id>
                <nombrelogro>Victoria magistral</nombrelogro>
                <descripcion>Gana una partida</descripcion>
                <completado>true</completado>
            </logro>
            <logro>
                <id>2</id>
                <nombrelogro>Maestro de la victoria</nombrelogro>
                <descripcion>Gana 5 partidas</descripcion>
                <completado>false</completado>
            </logro>
            <logro>
                <id>3</id>
                <nombrelogro>La X marca el lugar</nombrelogro>
                <descripcion>Gana una partida utilizando fichas X</descripcion>
                <completado>true</completado>
            </logro>
            <logro>
                <id>4</id>
                <nombrelogro>O-mazing Victory</nombrelogro>
                <descripcion>Gana una partida utilizando fichas O</descripcion>
                <completado>true</completado>
            </logro>
            <logro>
            	<id>5</id>
            	<nombrelogro>Tablas</nombrelogro>
                <descripcion>Empata una partida</descripcion>
                <completado>false</completado>
            
            </logro>
        </logros>
    </persona>
</listapersonas>
